baseURL = 'https://aadi123.github.io/'
languageCode = 'en-us'
title = 'abhyÄsa'
theme = 'risotto'

[params.theme]
palette = 'base16-onedark'

[params.about]
title = "Aaditya Murthy"
description = "Software Engineer. Musician. Boba Enthusiast."

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 12

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 12