baseURL = 'https://aadityamurthy.com/'
languageCode = 'en-us'
title = 'abhyÄsa'
theme = 'risotto'
sectionPagesMenu = "main"

[params.theme]
palette = 'base16-onedark'

[params.about]
title = "Aaditya Murthy"
description = "Software Engineer. Musician. Chess-Player. Boba Enthusiast."

[security]
  enableInlineShortcodes = true